apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ml044wxtm-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ml044wxtm-java-springboot-gitops